options:
  formatter: stylish
files:
  include: '**/*.scss'
  ignore:
    - 'assets/scss/inc/_icons.scss'
    - 'assets/scss/inc/_fonts.scss'
    - 'assets/scss/inc/_normalize.scss'
    - 'assets/scss/inc/_sprite.scss'
rules:
  # Attributes Quotes
  # ex: foo[id="X"]
  attribute-quotes:
    - 2
    - include: true
  # Border Zero
  border-zero:
    - 2
    - convention: 0
  # Brace Styles
  brace-style:
    - 2
    - style: "1tbs"
  # Da errores por todos lados  --> Lo he puesto a 0 - PACO
  # Class name format
  # ex: class-name or _class-name
  class-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  # Clean Import paths
  clean-import-paths:
    - 2
    - filename-extension: false
  # Declarations Before Nesting
  declarations-before-nesting: 2
  # Empty Args
  empty-args:
    - 2
    - include: true
  # Empty Line Between Blocks ¿? ¿?
  empty-line-between-blocks:
    - 0
    - include: false
    - allow-single-line-rulesets: true
  # Extends Before Declarations
  extends-before-declarations: 0
  # Extends Before Mixins
  extends-before-mixins: 0
  # Final Newline
  final-newline:
    - 1
    - include: true
  # Force Attribute Nesting
  force-attribute-nesting: 0
  # Force Element Nesting
  force-element-nesting: 0
  # Force Pseudo Nesting
  force-pseudo-nesting: 0
  # Function Name Format
  function-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  # Hex Length
  hex-length:
    - 2
    - style: short
  # Hex Notation
  hex-notation:
    - 2
    - style: uppercase
  # ID Name Format
  id-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  # Indentation
  indentation:
    - 1
    - size: 2
  # Leading Zero
  # ex: .5em
  leading-zero:
    - 2
    - include: false
    # Lo he cambiado a 0, no tengo ningun leading zero y aún así da el error. -> Paco
  # Max File Line Count
  max-file-line-count:
    - 1
    - lenght: 150
  # Max Line Length
  max-line-length:
    - 0
    - length: 100
  # Cambiada por que hay veces que metemos URL en el css.
  # mixin Name Format
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  # Mixin Before Declaration ¿? ¿?
  mixins-before-declarations: 0
  # Nesting Depth
  nesting-depth:
    - 2
    - max-depth: 5
  # No Attribute Selectors
  no-attribute-selectors: 0
  # No Color Hex
  no-color-hex: 0
  # Color Keyword
  no-color-keywords: 2
  # No Color Literals
  no-color-literals: 2
  # No Combinators
  no-combinators: 0
  # No CSS Comments
  # This is a good comment
  no-css-comments: 2
  # No Debug
  no-debug: 0
  # No Disallowed Properties ¿?
  no-disallowed-properties: 0
  # No Duplicate properties
  no-duplicate-properties: 2
  # No Empty Rulesets
  no-empty-rulesets: 2
  # No Extends
  no-extends: 0
  # No Ids
  no-ids: 0
  # No Important
  no-important: 2
  # No Invalid Hex
  no-invalid-hex: 2
  # No Mergeable Selectors
  no-mergeable-selectors: 2
  # No Misspelled properties
  no-misspelled-properties: 2
  # No Qualifying Elements ¿? ¿?
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: true
    - allow-element-with-class: true
    - allow-element-with-id: false
  # No Trailing Whitespace
  no-trailing-whitespace: 2
  # No Trailing Zero
  no-trailing-zero: 2
  # No Transition All
  no-transition-all: 0
  # No Universal Selectors
  no-universal-selectors: 2
  # No Url Domains
  no-url-domains: 1
  # No Url Protocols
  no-url-protocols: 0
  # No Vendor Prefixes ¿? ¿?
  no-vendor-prefixes: 0
  # No Warn
  no-warn: 0
  # One Declaration Per Line
  one-declaration-per-line: 2
  # Placeholder In Extend
  placeholder-in-extend: 0
  # Placeholder Name Format
  placeholder-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  # Property Sort Order
  property-sort-order:
    - 0
    - order: alphabetical
  # Property Units
  # ex. global --> ['em', 'px', 'rem', etc]
  property-units:
    - 0
    - global: []
  # Pseudo Element
  pseudo-element: 2
  # Quotes
  quotes:
    - 0
    - style: single
  #Lo he cambiado porque me sigue diciendo que falla y no encuentro el error. -> Lo he cambiado a 0
  # Shorthands values
  shorthand-values: 2
  # Single Line per Selector
  single-line-per-selector: 0
  # Space After Bang
  space-after-bang:
    - 2
    - include: false
  # Space After Colon
  space-after-colon: 2
  # Space After Comma
  space-after-comma: 2
  # Space Around Operator
  space-around-operator: 2
  # Space Before Bang
  space-before-bang: 2
  # Space Before Brace
  space-before-brace: 2
  # Space Before Colon
  space-before-colon: 2
  # Space Between Parens
  space-between-parens: 2
  # Trailing Semicolon
  trailing-semicolon: 2
  # Url Quotes
  url-quotes: 2
  # Variable For Property
  variable-for-property: 0
  # Variable Name Format
  variable-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  # Zero unit
  zero-unit:
    - 2
    - include: false
